namespace: argocd

helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    valuesInline:
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
